CREATE DATABASE VTA_DB  ON C: ALIAS VTA_DB WITH "VTA Data Persistance Layer";
UPDATE DB CFG FOR VTA_DB USING AUTO_MAINT ON;
UPDATE DB CFG FOR VTA_DB USING AUTO_TBL_MAINT ON;
UPDATE DB CFG FOR VTA_DB USING AUTO_RUNSTATS ON;
UPDATE ALERT CFG FOR DATABASE ON VTA_DB USING db.db_backup_req SET THRESHOLDSCHECKED YES;
UPDATE ALERT CFG FOR DATABASE ON VTA_DB USING db.tb_reorg_req SET THRESHOLDSCHECKED YES;
UPDATE ALERT CFG FOR DATABASE ON VTA_DB USING db.tb_runstats_req SET THRESHOLDSCHECKED YES;

CONNECT TO VTA_DB;

	CREATE SCHEMA VTA_DB_SCHEMA;
		COMMENT ON Schema VTA_DB_SCHEMA IS 'Schema for VTA Database';


	CREATE TABLE VTA_DB_SCHEMA.ROLES ( 
		ROLE_ID SMALLINT NOT NULL 
			GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , 
		ROLE_NAME VARCHAR (65) , 
		ROLE_DESCRIPTION VARCHAR (65)  , 
		CONSTRAINT CC1331144218172 PRIMARY KEY ( ROLE_ID)  
	) ;


	CREATE TABLE VTA_DB_SCHEMA.TRANSACTIONS ( 
		TRANSACTION_ID SMALLINT  NOT NULL  
			GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , 
		TRANSACTION_NAME VARCHAR (65) , 
		TRANSACTION_DESCRIPTION VARCHAR (65)  , 
		CONSTRAINT CC1331145202672 PRIMARY KEY ( TRANSACTION_ID)  
	) ;


	CREATE TABLE VTA_DB_SCHEMA.LIMITS ( 
		LIMIT_ID SMALLINT  NOT NULL  
			GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , 
		LIMIT_NAME VARCHAR (65) , 
		LIMIT_DESCRIPTION VARCHAR (65)  , 
		CONSTRAINT CC1331145431266 PRIMARY KEY ( LIMIT_ID)  
	) ;


	CREATE TABLE VTA_DB_SCHEMA.ROLE_TRANSACTION_LIMIT ( 
		LIMIT_AMOUNT DECIMAL (11, 2) , 
		LIMIT_AMOUNT_DESCRIPTION VARCHAR (65) , 
		ROLE_ID INTEGER  NOT NULL , 
		LIMIT_ID INTEGER  NOT NULL , 
		TRANSACTION_ID INTEGER  NOT NULL , 
		CONSTRAINT FKEY_RTL_L FOREIGN KEY (LIMIT_ID) REFERENCES VTA_DB_SCHEMA.LIMITS (LIMIT_ID)  
			ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION , 
		CONSTRAINT FKEY_RTL_R FOREIGN KEY (ROLE_ID) REFERENCES VTA_DB_SCHEMA.ROLES (ROLE_ID)  
			ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION , 
		CONSTRAINT FKEY_RTL_T FOREIGN KEY (TRANSACTION_ID) REFERENCES VTA_DB_SCHEMA.TRANSACTIONS (TRANSACTION_ID)  
			ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION  ) ;
			COMMENT ON TABLE VTA_DB_SCHEMA.ROLE_TRANSACTION_LIMIT IS 'Set Relation Role-Transaction-Limits';
			COMMENT ON VTA_DB_SCHEMA.ROLE_TRANSACTION_LIMIT ( LIMIT_AMOUNT IS 'VTA Limit Amount for Transactions', LIMIT_AMOUNT_DESCRIPTION IS 'Description for Limit Amounts for Transactions' 
	) ;
		ALTER TABLE VTA_DB_SCHEMA.ROLE_TRANSACTION_LIMIT ADD CONSTRAINT PKEY_RTL PRIMARY KEY ( ROLE_ID, LIMIT_ID, TRANSACTION_ID) ;


	CREATE TABLE VTA_DB_SCHEMA.PRIORITIES ( 
		PRIORITY_ID SMALLINT  NOT NULL  
			GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , 
		PRIORITY_NAME VARCHAR (65) , 
		PRIORITY_DESCRIPTION VARCHAR (65)  , 
		CONSTRAINT CC1331151271156 PRIMARY KEY ( PRIORITY_ID)  ) ;
		COMMENT ON TABLE VTA_DB_SCHEMA.PRIORITIES IS 'VTA Priorities for Transactions';
		COMMENT ON VTA_DB_SCHEMA.PRIORITIES ( PRIORITY_NAME IS 'Priority Name', PRIORITY_ID IS 'VTA Priority ID Incremental' 
	) ;


	CREATE TABLE VTA_DB_SCHEMA.AGENTS ( 
		AGENT_ID VARCHAR (10)  NOT NULL , 
		AGENT_FIRST_NAME VARCHAR (65) , 
		AGENT_LAST_NAME VARCHAR (65)  , 
		CONSTRAINT CC1331150623000 PRIMARY KEY ( AGENT_ID)  ) ;


	CREATE TABLE VTA_DB_SCHEMA.TRANSACTION_PRIORITY ( 
		PRIORITY_ID SMALLINT  NOT NULL , 
		TRANSACTION_ID SMALLINT  NOT NULL  , 
		CONSTRAINT PKEY_TP PRIMARY KEY ( PRIORITY_ID, TRANSACTION_ID) , 
		CONSTRAINT FKEY_TP_T FOREIGN KEY (TRANSACTION_ID) REFERENCES VTA_DB_SCHEMA.TRANSACTIONS (TRANSACTION_ID)  
			ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION , 
		CONSTRAINT FKEY_TP_P FOREIGN KEY (PRIORITY_ID) REFERENCES VTA_DB_SCHEMA.PRIORITIES (PRIORITY_ID)  
			ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION  
	) ;

	CREATE TABLE VTA_DB_SCHEMA.AGENT_ROLE ( 
		AGENT_ID VARCHAR (10)  NOT NULL , 
		ROLE_ID SMALLINT  NOT NULL  , 
		CONSTRAINT PKEY_AR PRIMARY KEY ( AGENT_ID, ROLE_ID) , 
		CONSTRAINT FKEY_AR_A FOREIGN KEY (AGENT_ID) REFERENCES VTA_DB_SCHEMA.AGENTS (AGENT_ID)  
			ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION , 
		CONSTRAINT FKEY_AR_R FOREIGN KEY (ROLE_ID) REFERENCES VTA_DB_SCHEMA.ROLES (ROLE_ID)  
			ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION  
	) ;






	CREATE TABLE VTA_DB_SCHEMA.CODES ( 
		CODE_ID SMALLINT  NOT NULL  
			GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , 
		CODE_TEXT VARCHAR (65) , 
		CODE_NAME VARCHAR (65) , 
		IS_DEFAULT CHARACTER (1)  NOT NULL  WITH DEFAULT '1' , 
		CODE_SEQUENCE INTEGER , EFFECTIVE_DATE TIMESTAMP , 
		VERSION_BEGIN INTEGER , 
		VERSION_END INTEGER  , 
		CONSTRAINT CC1331225825500 PRIMARY KEY ( CODE_ID)  
	) ;




	CREATE TABLE VTA_DB_SCHEMA.PROGRESS_INDICATORS ( 
		INDICATOR_ID SMALLINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , 
		INDICATOR_NAME VARCHAR (65) , 
		INDICATOR_DESCRIPTION VARCHAR (65)  , 
		CONSTRAINT CC1331226093984 PRIMARY KEY ( INDICATOR_ID)  
	) ;




	CREATE TABLE VTA_DB_SCHEMA.CATEGORIES ( 
		CATEGORY_ID SMALLINT  NOT NULL  
			GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE ) , 
		CATEGORY_NAME VARCHAR (65)  NOT NULL , 
		CATEGORY_TYPE VARCHAR (65)  NOT NULL , 
		CATEGORY_DESCRIPTION VARCHAR (65) , 
		IS_SYSTEM CHARACTER (1)  WITH DEFAULT '1' , 
		COMMENTS VARCHAR (65)  , 
		CONSTRAINT CC1331226292312 PRIMARY KEY ( CATEGORY_ID)  
	) ;




	CREATE TABLE VTA_DB_SCHEMA.CODE_CATEGORY ( 
		CODE_ID SMALLINT  NOT NULL , 
		CODE_CATEGORY_ID INTEGER  NOT NULL  , 
		CONSTRAINT FKEY_CC PRIMARY KEY ( CODE_ID, CODE_CATEGORY_ID) , 
		CONSTRAINT FKEY_CC_CAT FOREIGN KEY (CODE_CATEGORY_ID) 
			REFERENCES VTA_DB_SCHEMA.CATEGORIES (CATEGORY_ID)  ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION , 
		CONSTRAINT FKEY_CC_C FOREIGN KEY (CODE_ID) 
			REFERENCES VTA_DB_SCHEMA.CODES (CODE_ID)  ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION  
	) ;




	CREATE TABLE VTA_DB_SCHEMA.TRANSACTION_PROGRESS_INDICATOR ( 
		INDICATOR_ID SMALLINT  NOT NULL , 
		TRANSACTION_ID SMALLINT  NOT NULL  , 
		CONSTRAINT FKEY_TPI PRIMARY KEY ( INDICATOR_ID, TRANSACTION_ID) , 
		CONSTRAINT FKEY_TPI_T FOREIGN KEY (TRANSACTION_ID) 
			REFERENCES VTA_DB_SCHEMA.TRANSACTIONS (TRANSACTION_ID)  ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION , 
		CONSTRAINT FKEY_TPI_I FOREIGN KEY (INDICATOR_ID) 
			REFERENCES VTA_DB_SCHEMA.PROGRESS_INDICATORS (INDICATOR_ID)  ON DELETE CASCADE ON UPDATE RESTRICT ENFORCED  ENABLE QUERY OPTIMIZATION  
	) ;



CONNECT RESET;
