package main.java.com.boa.domain;
// default package
// Generated Mar 9, 2012 2:46:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Agents generated by hbm2java
 */
public class Agents implements java.io.Serializable {

	private String agentId;
	private String agentFirstName;
	private String agentLastName;
	private Set roleses = new HashSet(0);

	public Agents() {
	}

	public Agents(String agentId) {
		this.agentId = agentId;
	}

	public Agents(String agentId, String agentFirstName, String agentLastName,
			Set roleses) {
		this.agentId = agentId;
		this.agentFirstName = agentFirstName;
		this.agentLastName = agentLastName;
		this.roleses = roleses;
	}

	public String getAgentId() {
		return this.agentId;
	}

	public void setAgentId(String agentId) {
		this.agentId = agentId;
	}

	public String getAgentFirstName() {
		return this.agentFirstName;
	}

	public void setAgentFirstName(String agentFirstName) {
		this.agentFirstName = agentFirstName;
	}

	public String getAgentLastName() {
		return this.agentLastName;
	}

	public void setAgentLastName(String agentLastName) {
		this.agentLastName = agentLastName;
	}

	public Set getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set roleses) {
		this.roleses = roleses;
	}

}
