package main.java.com.boa.domain;
// default package
// Generated Mar 9, 2012 2:46:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	private short categoryId;
	private String categoryName;
	private String categoryType;
	private String categoryDescription;
	private Character isSystem;
	private String comments;
	private Set codeses = new HashSet(0);

	public Categories() {
	}

	public Categories(short categoryId, String categoryName, String categoryType) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.categoryType = categoryType;
	}

	public Categories(short categoryId, String categoryName,
			String categoryType, String categoryDescription,
			Character isSystem, String comments, Set codeses) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.categoryType = categoryType;
		this.categoryDescription = categoryDescription;
		this.isSystem = isSystem;
		this.comments = comments;
		this.codeses = codeses;
	}

	public short getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(short categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryType() {
		return this.categoryType;
	}

	public void setCategoryType(String categoryType) {
		this.categoryType = categoryType;
	}

	public String getCategoryDescription() {
		return this.categoryDescription;
	}

	public void setCategoryDescription(String categoryDescription) {
		this.categoryDescription = categoryDescription;
	}

	public Character getIsSystem() {
		return this.isSystem;
	}

	public void setIsSystem(Character isSystem) {
		this.isSystem = isSystem;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Set getCodeses() {
		return this.codeses;
	}

	public void setCodeses(Set codeses) {
		this.codeses = codeses;
	}

}
