package main.java.com.boa.domain;
// default package
// Generated Mar 9, 2012 2:46:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Codes generated by hbm2java
 */
public class CodesBO implements java.io.Serializable {

	private short codeId;
	private String codeText;
	private String codeName;
	private char isDefault;
	private Integer codeSequence;
	private Date effectiveDate;
	private Integer versionBegin;
	private Integer versionEnd;
	private Set categorieses = new HashSet(0);

	public CodesBO() {
	}

	public CodesBO(short codeId, char isDefault) {
		this.codeId = codeId;
		this.isDefault = isDefault;
	}

	public CodesBO(short codeId, String codeText, String codeName,
			char isDefault, Integer codeSequence, Date effectiveDate,
			Integer versionBegin, Integer versionEnd, Set categorieses) {
		this.codeId = codeId;
		this.codeText = codeText;
		this.codeName = codeName;
		this.isDefault = isDefault;
		this.codeSequence = codeSequence;
		this.effectiveDate = effectiveDate;
		this.versionBegin = versionBegin;
		this.versionEnd = versionEnd;
		this.categorieses = categorieses;
	}

	public short getCodeId() {
		return this.codeId;
	}

	public void setCodeId(short codeId) {
		this.codeId = codeId;
	}

	public String getCodeText() {
		return this.codeText;
	}

	public void setCodeText(String codeText) {
		this.codeText = codeText;
	}

	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	public char getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(char isDefault) {
		this.isDefault = isDefault;
	}

	public Integer getCodeSequence() {
		return this.codeSequence;
	}

	public void setCodeSequence(Integer codeSequence) {
		this.codeSequence = codeSequence;
	}

	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public Integer getVersionBegin() {
		return this.versionBegin;
	}

	public void setVersionBegin(Integer versionBegin) {
		this.versionBegin = versionBegin;
	}

	public Integer getVersionEnd() {
		return this.versionEnd;
	}

	public void setVersionEnd(Integer versionEnd) {
		this.versionEnd = versionEnd;
	}

	public Set getCategorieses() {
		return this.categorieses;
	}

	public void setCategorieses(Set categorieses) {
		this.categorieses = categorieses;
	}

}
