package main.java.com.boa.domain;
// default package
// Generated Mar 9, 2012 2:46:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Limits generated by hbm2java
 */
public class Limits implements java.io.Serializable {

	private short limitId;
	private String limitName;
	private String limitDescription;
	private Set roleTransactionLimits = new HashSet(0);

	public Limits() {
	}

	public Limits(short limitId) {
		this.limitId = limitId;
	}

	public Limits(short limitId, String limitName, String limitDescription,
			Set roleTransactionLimits) {
		this.limitId = limitId;
		this.limitName = limitName;
		this.limitDescription = limitDescription;
		this.roleTransactionLimits = roleTransactionLimits;
	}

	public short getLimitId() {
		return this.limitId;
	}

	public void setLimitId(short limitId) {
		this.limitId = limitId;
	}

	public String getLimitName() {
		return this.limitName;
	}

	public void setLimitName(String limitName) {
		this.limitName = limitName;
	}

	public String getLimitDescription() {
		return this.limitDescription;
	}

	public void setLimitDescription(String limitDescription) {
		this.limitDescription = limitDescription;
	}

	public Set getRoleTransactionLimits() {
		return this.roleTransactionLimits;
	}

	public void setRoleTransactionLimits(Set roleTransactionLimits) {
		this.roleTransactionLimits = roleTransactionLimits;
	}

}
