package main.java.com.boa.domain;
// default package
// Generated Mar 9, 2012 2:46:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Priorities generated by hbm2java
 */
public class Priorities implements java.io.Serializable {

	private short priorityId;
	private String priorityName;
	private String priorityDescription;
	private Set transactionses = new HashSet(0);

	public Priorities() {
	}

	public Priorities(short priorityId) {
		this.priorityId = priorityId;
	}

	public Priorities(short priorityId, String priorityName,
			String priorityDescription, Set transactionses) {
		this.priorityId = priorityId;
		this.priorityName = priorityName;
		this.priorityDescription = priorityDescription;
		this.transactionses = transactionses;
	}

	public short getPriorityId() {
		return this.priorityId;
	}

	public void setPriorityId(short priorityId) {
		this.priorityId = priorityId;
	}

	public String getPriorityName() {
		return this.priorityName;
	}

	public void setPriorityName(String priorityName) {
		this.priorityName = priorityName;
	}

	public String getPriorityDescription() {
		return this.priorityDescription;
	}

	public void setPriorityDescription(String priorityDescription) {
		this.priorityDescription = priorityDescription;
	}

	public Set getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set transactionses) {
		this.transactionses = transactionses;
	}

}
