package main.java.com.boa.domain;
// default package
// Generated Mar 9, 2012 2:46:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProgressIndicators generated by hbm2java
 */
public class ProgressIndicatorsBO implements java.io.Serializable {

	private short indicatorId;
	private String indicatorName;
	private String indicatorDescription;
	private Set transactionses = new HashSet(0);

	public ProgressIndicatorsBO() {
	}

	public ProgressIndicatorsBO(short indicatorId) {
		this.indicatorId = indicatorId;
	}

	public ProgressIndicatorsBO(short indicatorId, String indicatorName,
			String indicatorDescription, Set transactionses) {
		this.indicatorId = indicatorId;
		this.indicatorName = indicatorName;
		this.indicatorDescription = indicatorDescription;
		this.transactionses = transactionses;
	}

	public short getIndicatorId() {
		return this.indicatorId;
	}

	public void setIndicatorId(short indicatorId) {
		this.indicatorId = indicatorId;
	}

	public String getIndicatorName() {
		return this.indicatorName;
	}

	public void setIndicatorName(String indicatorName) {
		this.indicatorName = indicatorName;
	}

	public String getIndicatorDescription() {
		return this.indicatorDescription;
	}

	public void setIndicatorDescription(String indicatorDescription) {
		this.indicatorDescription = indicatorDescription;
	}

	public Set getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set transactionses) {
		this.transactionses = transactionses;
	}

}
