package main.java.com.boa.domain;
// default package
// Generated Mar 9, 2012 2:46:44 PM by Hibernate Tools 3.4.0.CR1

/**
 * RoleTransactionLimitId generated by hbm2java
 */
public class RoleTransactionLimitId implements java.io.Serializable {

	private int roleId;
	private int limitId;
	private int transactionId;

	public RoleTransactionLimitId() {
	}

	public RoleTransactionLimitId(int roleId, int limitId, int transactionId) {
		this.roleId = roleId;
		this.limitId = limitId;
		this.transactionId = transactionId;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public int getLimitId() {
		return this.limitId;
	}

	public void setLimitId(int limitId) {
		this.limitId = limitId;
	}

	public int getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleTransactionLimitId))
			return false;
		RoleTransactionLimitId castOther = (RoleTransactionLimitId) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& (this.getLimitId() == castOther.getLimitId())
				&& (this.getTransactionId() == castOther.getTransactionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getLimitId();
		result = 37 * result + this.getTransactionId();
		return result;
	}

}
