package main.java.com.boa.domain;
// default package
// Generated Mar 9, 2012 2:46:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private short roleId;
	private String roleName;
	private String roleDescription;
	private Set roleTransactionLimits = new HashSet(0);
	private Set agentses = new HashSet(0);

	public Roles() {
	}

	public Roles(short roleId) {
		this.roleId = roleId;
	}

	public Roles(short roleId, String roleName, String roleDescription,
			Set roleTransactionLimits, Set agentses) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDescription = roleDescription;
		this.roleTransactionLimits = roleTransactionLimits;
		this.agentses = agentses;
	}

	public short getRoleId() {
		return this.roleId;
	}

	public void setRoleId(short roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	public Set getRoleTransactionLimits() {
		return this.roleTransactionLimits;
	}

	public void setRoleTransactionLimits(Set roleTransactionLimits) {
		this.roleTransactionLimits = roleTransactionLimits;
	}

	public Set getAgentses() {
		return this.agentses;
	}

	public void setAgentses(Set agentses) {
		this.agentses = agentses;
	}

}
