package main.java.com.boa.domain;
// default package
// Generated Mar 9, 2012 2:46:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Transactions generated by hbm2java
 */
public class Transactions implements java.io.Serializable {

	private short transactionId;
	private String transactionName;
	private String transactionDescription;
	private Set prioritieses = new HashSet(0);
	private Set roleTransactionLimits = new HashSet(0);
	private Set progressIndicatorses = new HashSet(0);

	public Transactions() {
	}

	public Transactions(short transactionId) {
		this.transactionId = transactionId;
	}

	public Transactions(short transactionId, String transactionName,
			String transactionDescription, Set prioritieses,
			Set roleTransactionLimits, Set progressIndicatorses) {
		this.transactionId = transactionId;
		this.transactionName = transactionName;
		this.transactionDescription = transactionDescription;
		this.prioritieses = prioritieses;
		this.roleTransactionLimits = roleTransactionLimits;
		this.progressIndicatorses = progressIndicatorses;
	}

	public short getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(short transactionId) {
		this.transactionId = transactionId;
	}

	public String getTransactionName() {
		return this.transactionName;
	}

	public void setTransactionName(String transactionName) {
		this.transactionName = transactionName;
	}

	public String getTransactionDescription() {
		return this.transactionDescription;
	}

	public void setTransactionDescription(String transactionDescription) {
		this.transactionDescription = transactionDescription;
	}

	public Set getPrioritieses() {
		return this.prioritieses;
	}

	public void setPrioritieses(Set prioritieses) {
		this.prioritieses = prioritieses;
	}

	public Set getRoleTransactionLimits() {
		return this.roleTransactionLimits;
	}

	public void setRoleTransactionLimits(Set roleTransactionLimits) {
		this.roleTransactionLimits = roleTransactionLimits;
	}

	public Set getProgressIndicatorses() {
		return this.progressIndicatorses;
	}

	public void setProgressIndicatorses(Set progressIndicatorses) {
		this.progressIndicatorses = progressIndicatorses;
	}

}
